name: Lint

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: Lint
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
        with:
          cli: 1.12.1.1550
      - name: Cache Clojure dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clj-deps-${{ hashFiles('deps.edn') }}
      - name: Validate projects
        run: clojure -X:validate-projects
      - name: cljfmt
        run: clojure -M:cljfmt check
      - name: clj-kondo
        run: clojure -M:clj-kondo --parallel --fail-level error --lint src
